services:

  dynamodb-local:
    container_name: dynamodb-local
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    volumes:
      - ./docker/dynamodb:/home/dynamodblocal/data

  app:
    build: .                      # builds from the Dockerfile
    container_name: spring-app
    ports:
      - "8081:8080"               # direct access to app
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_REGION=us-east-1
      # point to docker service name
      - aws.dynamodb.endpoint=http://dynamodb-local:8000
      # set profile to local for now to run identical as native
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092

    depends_on:
      - dynamodb-local
      - kafka
      - kafka-ui

  nginx:
    image: nginx:alpine
    container_name: nginx-gateway
    ports:
      - "8080:80"                 # access the API using this
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

  redis:
    image: redis:8.4.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis:/data  # useful only to enable persistence, will additionally need to add "command" attribute to start redis with persistence.

  kafka:
    image: apache/kafka:4.1.1
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"     # Host access
      - "29092:29092"  # Container-to-container access
      - "9093:9093"   # Controller (KRaft)

    environment:
      # ----- KRaft Core -----
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: "1"
      KAFKA_CLUSTER_ID: "dev-cluster-1"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

      # ----- Listeners -----
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092,INTERNAL://kafka:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"

      # ----- Storage -----
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"

      # ----- Dev-friendly defaults -----
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"

      # ----- Memory -----
      KAFKA_JVM_PERFORMANCE_OPTS: "-Xms256m -Xmx512m"

    volumes:
      - kafka-data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8082:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:29092"
    depends_on:
      - kafka

  prometheus:
    image: prom/prometheus:v3.9.1
    container_name: prometheus
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:12.3
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

  loki:
    image: grafana/loki:3.6.4
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:3.6.4
    container_name: promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./docker/promtail/promtail.yaml:/etc/promtail/promtail.yaml:ro
    command: -config.file=/etc/promtail/promtail.yaml

volumes:
  kafka-data:
  grafana-data:
