services:

  dynamodb-local:
    container_name: dynamodb-local
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    volumes:
      - ./docker/dynamodb:/home/dynamodblocal/data

  app:
    build: .                      # builds from the Dockerfile
    container_name: spring-app
    ports:
      - "8081:8080"               # direct access to app
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_REGION=us-east-1
      # point to docker service name!
      - SPRING_CLOUD_AWS_DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      # or if using pure aws-sdk-v2:
      # - aws.dynamodb.endpoint=http://dynamodb-local:8000
    depends_on:
      - dynamodb-local

  nginx:
    image: nginx:alpine
    container_name: nginx-gateway
    ports:
      - "8080:80"                 # access the API using this
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

  redis:
      image: redis:8.4.0-alpine
      container_name: redis
      ports:
        - "6379:6379"
      volumes:
        - ./docker/redis:/data  # useful only to enable persistence, will additionally need to add "command" attribute to start redis with persistence.